version: 2.1
orbs:
  orb-tools: circleci/orb-tools@12.0
  rollout: {}

filters: &filters
  tags:
    only: /.*/

release-filters: &release-filters
  branches:
    ignore: /.*/
  tags:
    only: /^v[0-9]+\.[0-9]+\.[0-9]+$/

workflows:
  test-deploy:
    jobs:
      - rollout/build_and_push_server_to_aws_ecr:
          name: build_and_push_server_to_aws_ecr
          path_to_dockerfile: ~/project/sample
          path_to_build_dir: ~/project/sample
          repo_name: rollout-sample
          filters: *filters
      - orb-tools/pack:
          filters: *release-filters
      - orb-tools/publish:
          orb_name: studion/rollout
          vcs_type: << pipeline.project.type >>
          pub_type: production
          requires:
            - orb-tools/pack
          context: orb-publishing
          filters: *release-filters
